name: qr_flutter
description: A QR code library for Flutter.
version: 1.1.1
author: Luke Freeman <freeman.luke@gmail.com>
homepage: https://twitter.com/lukeaf

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^1.0.0

flutter:
  uses-material-design: false